version: '2'
services:
  grpc_api:
    command: dockerize -wait tcp://postgres.grpc_python_example.site:5432 ./scripts/run-grpc-api.dev.sh
    image: grpc_python_example
    depends_on:
      - postgres
    environment:
      # must bind to [::] for port forwarding to work properly
      - HOST=[::]
      - PORT=50051
      - DATABASE_URL=postgresql://postgres@postgres.grpc_python_example.site:5432/grpc_python_example
    networks:
      default:
        aliases:
          - grpc_api.grpc_python_example.site
    ports:
      - "50051:50051"
    volumes:
      - ./:/opt/grpc_python_example/
  http_api:
    command: dockerize -wait tcp://grpc_api.grpc_python_example.site:50051 -timeout 30s make run-http-api
    image: grpc_python_example
    depends_on:
      - grpc_api
    environment:
      - GRPC_API_URL=grpc_api.grpc_python_example.site:50051
    networks:
      default:
        aliases:
          - http_api.grpc_python_example.site
    ports:
      - "4000:4000"
    volumes:
      - ./:/opt/grpc_python_example/
  postgres:
    image: postgres:9.6
    networks:
      default:
        aliases:
          - postgres.grpc_python_example.site
    ports:
      - "5432:5432"
